SOURCES = hanabi_types.ml game.ml hanabi.ml base_player.ml
PACKS   = core sexplib sexplib.syntax comparelib comparelib.syntax
RESULT  = hanabi.exe
THREADS = y
OCAMLFLAGS = -syntax camlp4o
PREDS = camlp4o

-include OCamlMakefile
