SOURCES = hanabi_types.ml hanabi.ml game.ml
PACKS   = core sexplib sexplib.syntax comparelib comparelib.syntax
RESULT  = hanabi.exe
THREADS = y
OCAMLFLAGS = -syntax camlp4o
PREDS = camlp4o

-include OCamlMakefile
