SOURCES = hanabi_types.ml game.ml knowledge.ml base_player.ml players.ml hanabi.ml
PACKS   = core core_extended sexplib sexplib.syntax comparelib comparelib.syntax
RESULT  = hanabi.exe
THREADS = y
OCAMLFLAGS = -syntax camlp4o -g
OCAMLLDFLAGS = -g
PREDS = camlp4o

-include OCamlMakefile
